### PR TITLE
refactored main.py to make it DRY

### PR DESCRIPTION
**Pull request by keystroke3**
### Changes
The line `streamlink.streams(request.args.get('streaming-ip')` was repeated several times throughout the code. I corrected this by creating a function and that does the query and stores response a variable. I am not sure if `streamlink.streams()` queries the host each time it is called or if the initial response is cached by python. If the former is true, then the refactor reduces the number of queries to the host to just one per request. This would help in reducing the chance of getting a 429 error from the host.   
### New
Another change made, is how the server handles quality queries. If a valid quality string is provided, a matching link is served. Otherwise the list of valid qualities is served. This means that any quality query string that does not match any available quality, including the previous `unsure`, will return the list.  
Tests performed on the old and new code show performance parity with the refactored code pulling ahead in some cases.  
### Proposal
On the subject of quality queries, I propose adding an option to serve multiple quality links per request if more than one quality is passed.

### CODE REVIEW

**Review by LaneSh4d0w — APPROVED** [review]
Perfect, thanks for your PR !

About the quality links... I could do that by reading the number of qualities being given to me. I'll only show them, as a matter of fact.

**Comment by keystroke3** [comment]
I was thinking of doing this for those who use scripts to generate m3u8 files. A json object can be returned in response to multiple quality or to a `json` or `api` parameters. For those using the browser, just listing the links is fine. An m3u8 file can also be created, the same way linkastream does it in the browser, but this may be unnecessary. I was planning on using the code in my own server for vidio.com support.

**Comment by LaneSh4d0w** [comment]
There's absolutely no problem if you wanna use my code in your server, feel free to do so :)

I could actually implement a sort of API actually, with a specific endpoint that gets all links if no quality is being asked, and specific links if it's the case.

**Comment by keystroke3** [comment]
Yes, that would be best. If someone wants multiple links, they can use the api. This would leave the default url uninterrupted. I will start working on it this evening.

**Comment by keystroke3** [comment]
How will we handle multi-quality requests on non api endpoint? I have finished making a bare bones api, but can't decide on how to deal with multi-quality streams. Do we just send  a string or create an m3u8 file with all of them and send that instead, because we can't redirect.

**Comment by LaneSh4d0w** [comment]
We could create an adaptive link with multiple links in it, that's a good
idea.

**Comment by keystroke3** [comment]
Does streamlink have a way of figuring out the bandwidth and picture Width x Height? If it doesn't, I will have to set them manually, depending on the quality.

**Comment by LaneSh4d0w** [comment]
> 
> 
> Does streamlink have a way of figuring out the bandwidth and picture Width x Height? If it doesn't, I will have to set them manually, depending on the quality.

I think you can, if you ask Streamlink to be on verbose, I think it spits out the actual height and width.

**Comment by keystroke3** [comment]
I just went ahead and left that directive out. For the bandwidth I just used a range and values that youtube uses.

**Pull request merged**
