### PR TITLE
Completed basic api

### PR DESCRIPTION
**Pull request by keystroke3**
The basic api is complete. I have tested it on vlc, mpv and kodi and they all seem to work ok. I have not tested the bandwidth switching during playback. Please perform some more tests on your end before deploying to production.

### CODE REVIEW

**Comment by LaneSh4d0w** [comment]
Testing on my side and i'll see if it goes well. I've seen the FIXMEs and TODOs, i'm gonna take a look at those.

**Comment by LaneSh4d0w** [comment]
Tested on one hosted stream, works fine, the only thing is the name doesn't change.

**Comment by keystroke3** [comment]
What name?

**Comment by LaneSh4d0w** [comment]
> What name?

I've tried with https://twitch.tv/Aledz_

**Comment by keystroke3** [comment]
When I try it, I get the error:
`Could not get the link, Streamlink couldn't read https://www.twitch.tv/Aledz_`
Is it possible to get error messages from streamlink? When I run `streamlink.stream()` from python interactive shell, I get an empty dict object just like in the server

**Comment by LaneSh4d0w** [comment]
Weird, it works for me

**Comment by keystroke3** [comment]
>That's quite interesting, it doesn't work on the server but works with my IP.   
It's the reverse for me. Works on my server, but doesn't work on my home computer.

**Comment by LaneSh4d0w** [comment]
> >That's quite interesting, it doesn't work on the server but works with my IP.   
> 
>It's the reverse for me. Works on my server, but doesn't work on my home computer.

Interesting...

**Comment by keystroke3** [comment]
Linkastream just says the stream is offline. It uses a different program to query.

**Comment by keystroke3** [comment]
> Changes were pushed on server, try and see.   

What is the address for your instance?

**Comment by LaneSh4d0w** [comment]
Something even more interesting... it started to work on my server : https://query-streamlink.lanesh4d0w.repl.co/api?streaming-ip=https://twitch.tv/Aledz_

Update your streamlink library, it might be this.

**Comment by keystroke3** [comment]
I am using the latest release v2.2,0

**Comment by LaneSh4d0w** [comment]
That's pretty weird indeed, validators worked on my side. The REPL server also uses validators and it's got it using Poetry... so it's indeed weird.

**Comment by LaneSh4d0w** [comment]
I'll need to make it work on Vercel, because REPL is going to make me restart the server every time.

Merging this PR since it seems to work, but random issues that aren't on our side seems to happen.

**Comment by keystroke3** [comment]
I guess we can hold this bug for later. If a channel is hosting another, it is technically offline. Probably the content that the user is trying to access by using this tool will not be available on the guest channel. If they do want the guest channel content, they can query for it directly.

**Comment by keystroke3** [comment]
Does streamlink work with youtube?
When I try to query any youtube live, premier or VOD, I am only getting a `PluginError`.
For example, with https://youtube.com/c/nasa/live:
```
Unable to open URL: https://youtube.com/get_video_info (404 Client Error: Not Found for url: https://www.youtube.com/get_video_info?video_id=nA9UZF-SZoQ&html5=1&el=detailpage)
```
Am I supposed to load the plugin?

**Pull request merged**
